### ISSUE TITLE
Stability of CSV files

### ISSUE THREAD

**Issue by owahltinez** [tomwhite/covid-19-uk-data#25]
Hi @tomwhite , first of all thanks so much for this -- awesome work! I am now using your CSV files to add region-level data to my [Open COVID-19 project](https://github.com/open-covid-19/data).

I am currently pulling the CSV files from the GitHub Raw cache ([like this one](https://raw.githubusercontent.com/tomwhite/covid-19-uk-data/master/data/covid-19-indicators-uk.csv)) and I wanted to understand how stable these files are, whether you are likely to change the name, location, format, etc. In case of any changes, how can I be notified so I can update my scripts appropriately?

**Comment by tomwhite** [comment]
Hi @owahltinez - glad this is useful.

So far I haven't changed the format of the data being published. I can't guarantee no changes since I am at the mercy of upstream changes, but I'll try to keep them backwards compatible where possible (e.g. by adding new fields or files). I will announce changes in the top-level README, so you could keep an eye on that.

**Comment by nanjizal** [comment]
@owahltinez would be interested in possible collaborations, I have been feeding off the raw for few weeks now, the main problem is gov inconsistency with naming and areas, I don't have much time to work on presentation but have been trying to improve it on weekends while tweaking the parsing to deal with some changes.
https://nanjizal.github.io/covid19/bin/index.html?test5

**Comment by owahltinez** [comment]
@nanjizal that animation is very cool! How did you make it?

I don't think my work will help you much, since I'm only parsing second-level data for UK and in this case that's only Wales, Scotland, England and North Ireland.

**Comment by nanjizal** [comment]
I marry up the git raw data to lat/long csv data with some fixes ( like trimming spaces )
https://github.com/nanjizal/covid19/tree/master/data
and then convert them to 2D ( porting this algorithm from python to haxe js ) 
https://github.com/nanjizal/latLongUK/blob/master/src/latLongUK/LatLongUK.hx
I created from lots of lines a UK outline a few year ago ( I used flash ) recently extracted the raw data and put it in code, I don't much like canvas drawing so I have some code that makes it more like flash turtle graphics ( see htmlHelper ).
https://github.com/nanjizal/uk/blob/master/src/uk/UK.hx
The animation, I inject css loop into the js to give me basic frame animation and setup a canvas
https://github.com/nanjizal/htmlHelper
I divert the haxe trace to a textfield on screen used for all text ... lazy approach!
and every so many frames I render a day ( not every frame using mod ). I pick a colour from a colour wheel 1 to 24 related to size.  
https://github.com/nanjizal/pallette/blob/master/pallette/ColorWheel24.hx
Each circle is drawn with triangles so that I can change the implementation to webgl easily if I want, the radius is related to total cases, added auto scaling based on largest plot yesterday so they don't get too big.
Previously I was overlaying data circles but I have now changed it I use one canvas to draw the background uk with the curved grid and then draw that to the main canvas that is cleared every time it's drawn.
https://github.com/nanjizal/covid19/blob/master/src/covid19/Main.hx
I use date time from here
https://github.com/RealyUniqueName/DateTime#datetime
So mostly I have some of my own helpers to make html canvas easier and loading and parsing csv at character level.

I am looking to mix it with OpenFL and haxeui to add some controls see my 'covid19ofl' repo, but only setup project so far not yet wired up controls.

**Comment by jamierees** [comment]
Can anyone help me I am looking for the data in csv format for Scotland, Wales and Ireland.  If anyone has a link let me know

**Comment by tomwhite** [comment]
@jamierees see the links here: https://github.com/tomwhite/covid-19-uk-data#data-files

**Comment by nanjizal** [comment]
@tomwhite this is your git raw csv feed it's perhaps more useful for any web user than readme.
'https://raw.githubusercontent.com/tomwhite/covid-19-uk-data/master/data/covid-19-cases-uk.csv';
