### ISSUE TITLE
England cases breakdown

### ISSUE THREAD

**Issue by AirAllergy** [tomwhite/covid-19-uk-data#41]
The England cases breakdown are one-day shifted (e.g. the data of 16/04/2020 are actually those of 15/04/2020).

Also the breakdown data from the new dashboard can date back to day 1 of outbreak, which seems to be constantly revised on a daily basis. And the breakdown of Hackney and City of London is provided throughout the whole time series. It seems reasonable to replace the England breakdown with these new data, instead of attaching daily ones to the existing database.

**Comment by tomwhite** [comment]
@AirAllergy thanks for raising this. You're right. I have a script (compare_phe_historical.py) that compares the old PHE data (Historic COVID-19 Dashboard Data.xlsx) with the data in this repo, and it agreed for the most part. That spreadsheet is no longer being updated. Data from the new PHE dashboard diverges to a much larger degree, presumably because of the daily revisions that you mention.

I'll work on bringing the data in this repo up to date.

**Comment by AirAllergy** [comment]
@tomwhite I realise that they have started to use the specimen date rather than the reporting date in terms of England cases. Please ignore my first paragraph.

Great work you have done, cheers and stay safe!
