### ISSUE TITLE
Only new death data in Covid-19-totals-uk.csv

### ISSUE THREAD

**Issue by ahughf** [tomwhite/covid-19-uk-data#48]
Since the change by UK Gov so that reported death numbers now including more than just those for confirmed cases in hospital it looks like you are missing the tests and confirmed cases numbers in this file.

**Comment by tomwhite** [comment]
@ahughf this wasn't due to the change in how death numbers were reported, but because https://www.gov.uk/guidance/coronavirus-covid-19-information-for-the-public#number-of-cases-and-deaths hasn't been updated for 29 April 2020.

In the meantime, I've manually entered the numbers from this tweet https://twitter.com/DHSCgovuk/status/1255544385082712066.

Thanks for reporting the issue!
