### ISSUE TITLE
Tests & Tested

### ISSUE THREAD

**Issue by Simples80** [tomwhite/covid-19-uk-data#50]
Hi Tom, I was trying to locate and compare the historical data for the number tests issued (Tests) against the number of Tested samples. Yesterdays figures were 81,611 Tests with 54,575 Tested.
I can see the 54,575 in the CSV file but not the Tests column?

**Comment by tomwhite** [comment]
Hi @Simples80 - "tests" refers to "people tested" since that is what has been reported since the beginning, and I've been striving to maintain backwards compatibility (this is noted at https://github.com/tomwhite/covid-19-uk-data#data-files). More recently the number of tests performed has been reported, you can find these figures in covid-19-tests-uk.csv. Hope that helps.
