### ISSUE TITLE
Test and Confirmed cases data missing from covid-19-uk-data 19 May

### ISSUE THREAD

**Issue by ahughf** [tomwhite/covid-19-uk-data#57]
Yesterdays (19 May) Tests and confirmedCases data is missing from file covid-19-uk-data. Sorry if this is because the source data wasn't published by UK Govt.

**Comment by tomwhite** [comment]
Yes, this is because those numbers were not available yesterday. They have been published today (20 May).

**Comment by ahughf** [comment]
Will we ever get the numbers for 19th do you think? (Your csv and raw data files are still showing a gap for the 19th.)

**Comment by tomwhite** [comment]
Historical testing data is not being published (yet), so there will be a gap until PHE/DHSC start publishing a complete dataset I'm afraid.

**Comment by gfaggio** [comment]
Hi Tom,

Considering data from May19 onwards, the variables totalpositive and dailypositive in the file 'covid-19-tests-uk.csv' are not consistent. In fact, the variable totalpositive is lower in May20 than May19.
When you have time, could you please look into it?

Many thanks!
Giulia

**Comment by svavassori** [comment]
Hello Giulia,

The consistency problem between DailyPositive and the TotalPositive is long lasting.

As you can see in the picture here below, the sum of daily and yesterday's total isn't always equals to today's total (red on column **I**).
Column **J** is the cumulative sum of DailyPositive since 2020-04-08: it seems they tried to fix the difference and this causes the inconsistency you noticed.

![UK-totals](https://user-images.githubusercontent.com/1374430/82713782-84778000-9c8c-11ea-9a7d-da58a7e954d0.png)

**Comment by gfaggio** [comment]
Mny thanks for your help!
Giulia
